name: "exclude-sensitive-repos"
description: 'Exclude repos tagged with "sensitive" from an app installation'
author: "withgraphite"

inputs:
  classic-pat:
    description: |
      A classic PAT with `repo` permissions. This token will be used to manage 
      the installed repositories on each of the app installations and must 
      have access to the owners in question.
    required: true

  owners:
    description: |
      An array of objects with the following properties:  
      - `login` (required): the GitHub login of the owner (e.g. 'withgraphite')
      - `installId` (required): the ID of the app installation to manage 
        (e.g. 23731826)
      - `fineGrainedPat` (required): a fine-grained PAT that must have access 
        to the owner and contain the 'Custom properties' organization scope to 
        consume the custom properties API endpoint 
      - `skip` (optional): if `true`, the owner will be skipped
    required: true

runs:
  using: node20
  main: dist/index.js
